version: '3'

services:
  redis:
    image: redis
    volumes:
      - redis_db_data:/data/ela/redis
    restart: always
    
  mongo:
      image: mongo
      restart: always
      volumes: 
        - mongo_db_data:/data/ela/mongo

  admin:
      image: admin
      volumes:
        - ela_app_admin:/app/dist
  
  ela: 
    depends_on: 
      - redis
      - mongo
    image: ela
    restart: always
    ports:
      - 4221:4221
    environment: 
      MONGO_HOST: mongo
      REDIS_HOST: redis
    volumes: 
      - ela_app:/app

  mongo-express:
    image: mongo-express
    restart: alwagitys
    ports:
      - 8081:8081

  nginx:
    depends_on:
      - ela
    image: nginx
    ports:
      - 80:80
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ela_app_admin:/usr/share/nginx/html

volumes: 
  ela_app:
  ela_app_admin:
  redis_db_data: 
  mongo_db_data: